### ISSUE TITLE
Boosting post

### ISSUE THREAD

**Issue by xsuchy** [NicolasConstant/BirdsiteLive#35]
Currently, the posts cannot be boosted. It would be nice to be able to boost them.

**Comment by NicolasConstant** [comment]
Yes and unfortunately it's "by design": I have described the reason in my first announcement of the project [here](https://write.as/nicolas-constant/working-on-my-first-activitypub-application), but here is a quick summary: 
* people and admins tends to dislike twitter-bots because they fills public TL with people/data that aren't on the fediverse (I even seen admin blocking accounts/instances doing that for this very reason)
* that's why I'm publishing all content in the `follower-only` mode
* but follower-only can't be boosted by design... 😕

**Comment by xsuchy** [comment]
ACK. Thank you for the explanation.

**Comment by nytpu** [comment]
Sorry to return to a closed issue, but couldn't you post to unlisted (i.e. allows boosting and showing up to followers but doesn't show up on public timelines by default)? It seems that you do it by setting the post object's `to` the followers collection like for followers-only, but you then set the `cc` field to the public collection (see here: https://socialhub.activitypub.rocks/t/visibility-to-cc-mapping/284/2).

[This isn't formally supported in ActivityPub itself](https://www.w3.org/TR/activitypub/#client-addressing), but it seems to be a de-facto standard, and is implemented by [Mastodon](https://github.com/tootsuite/mastodon/blob/0b72aecab31878d5e846f86c793f554a9f97f3ab/app/lib/activitypub/tag_manager.rb#L111-L112), [Pleroma](https://git.pleroma.social/pleroma/pleroma/-/blob/c4b4258374e73ca4a6e3f3b30e3a8dad0ce40039/lib/pleroma/web/activity_pub/activity_pub.ex#L1064-1074), [PixelFed](https://github.com/pixelfed/pixelfed/blob/7a234ccd4c2a4390d61f32487fd6307ca903d6ce/app/Status.php#L386-L391), and presumably more, I just didn't feel like going and looking.
