### ISSUE TITLE
[Feature Request] Preload profiles with most recent tweets

### ISSUE THREAD

**Issue by garritfra** [NicolasConstant/BirdsiteLive#78]
It would be nice, if the user could see the most recent tweets of a person, when they are looked up.

## Considerations

- How does this impact API key usage?

**Comment by NicolasConstant** [comment]
Unfortunately it's not really possible due to how federation is working: you only see the account's federated statuses with your instance (not only with BirdsiteLIVE, it's the case will all ActivityPub services). 
Also, since I only publish statuses on `follower-only` mode, even if _there is_ federated statuses, you will only be able to see them if you follow the account and refresh it. Not ideal. 

The federation is quite tricky on this aspect, and most of the time we only have a partial view of the remote content from our instance, some clients like Sengi do fetch remotely some extra-data to enhance the view, but it's a bit a hacky workaround (but someone could totally create the same thing client-side: when a BirdsiteLIVE account is detected, it could fetch some data from Twitter and display it).
